name: Build OpenWrt Packages

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.tag }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - aarch64_generic
          - x86_64
        tag:
          - openwrt-24.10
          
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Initialization environment
        run : |
          git config --global user.email "OPPEN321@users.noreply.github.com"
          git config --global user.name "actions-user"
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: Free disk space
        if: steps.detect.outputs.pkgs != ''
        run: |
          sudo rm -rf /usr/lib/{jvm,llvm} /usr/local /usr/src/* /var/lib/gems /var/lib/mysql /var/lib/snapd /etc/skel /opt/{microsoft,az,hostedtoolcache,cni,mssql-tools,pipx} /usr/share/{az*,dotnet,swift,miniconda,gradle*,java,kotlinc,ri,sbt} /root/{.sbt,.local,.npm} /usr/libexec/gcc/x86_64-linux-gnu/14 /usr/lib/x86_64-linux-gnu/{*clang*,*LLVM*} /home/linuxbrew
          
      - name: Build
        uses: sbwml/openwrt-gh-action-sdk@helloworld
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: chinadns-ng dns2socks dns2socks-rust dns2tcp geoview hysteria ipt2socks lua-neturl luci-app-homeproxy luci-app-nikki luci-app-openclash luci-app-passwall luci-app-passwall2 luci-app-ssr-plus microsocks naiveproxy nikki pdnsd redsocks2 shadow-tls shadowsocks-libev shadowsocks-rust shadowsocksr-libev simple-obfs sing-box tcping trojan trojan-plus tuic-client v2ray-core v2ray-geodata v2ray-plugin xray-core xray-plugin
          IGNORE_ERRORS: true

      - name: Build Packages
        if: steps.detect.outputs.pkgs != ''
        uses: sbwml/openwrt-gh-action-sdk@helloworld
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.tag }}
          FEEDNAME: packages_ci
          PACKAGES: ${{ env.PACKAGES }}
          KEY_BUILD: ${{ secrets.sign_key }}
          NO_REFRESH_CHECK: true
          IGNORE_ERRORS: true

      - name: Upload artifacts
        if: steps.detect.outputs.pkgs != ''
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.tag }}-${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
          
      - name: Artifact packages
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.tag }}-${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
          
      - name: Zip packages
        run: |
          zip -j ${{ matrix.arch }}-${{ matrix.sdk }}.zip bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
          echo -e "## ðŸ“… æ›´æ–°è®¡åˆ’\n" > release.txt
          echo -e "- ðŸ•’ æ¯æ—¥è‡ªåŠ¨æ£€æµ‹ä¸Šæ¸¸æ›´æ–°\n" >> release.txt
          echo -e "- ðŸ”„ å¦‚æœ‰å˜åŠ¨åˆ™è‡ªåŠ¨è§¦å‘åŒæ­¥æŽ¨é€\n" >> release.txt
          echo -e "- ðŸ“¬ ä¿æŒä¸Žä¸Šæ¸¸ä»“åº“çš„ç‰ˆæœ¬ä¸€è‡´æ€§\n" >> release.txt

      - name: Upload packages
        uses: ncipollo/release-action@main
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          artifacts: "${{ matrix.arch }}-${{ matrix.sdk }}.zip"
          allowUpdates: true
          replacesArtifacts: true
          bodyFile: "release.txt"
          tag: ${{ matrix.arch }}
